name = "coil-former"
main = "build/worker.js"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "coil.w7hak.com/*", zone_name = "w7hak.com" }
]

[site]
bucket = "./dist"

[build]
command = "npm run build"
